### ISSUE TITLE
non-parameterized query value is rejected

### ISSUE THREAD

**Issue by jsparkes** [hoodunit/purescript-payload#16]
I have the following in an api Spec:
```
records ::
                        GET "/records?query=<search>&fields=doc_number&limit=<limit>"
                        -- GET "/records?query=<search>&limit=<limit>&fields=<fields>"
                          { query :: { search :: String, limit :: Int, fields :: String }
                          , response :: Data.SearchResult
                          }
                    }
```
and get this error when compiling:
```
Invalid query spec: query param key name must start with opening '<', e.g. limit=<limit>
Path: '/projects/<project>/collections/<collection>/records?query=search>&fields=doc_number&limit=<limit>'
```
I believe the changes to avoid query literals went a little too far in rejecting this case.   I can easily work around it by defining fields as a query parameter and passing in a value.

I could add a test case, but I'm hoping that this is easy enough to reproduce.

It's a tiny glitch in a great package for defining REST API clients.  I'm going to try the server side next.

**Comment by hoodunit** [comment]
So am I understanding correctly in that you want to encode a request with exactly the literal `doc_number` as in `http://example.com/?fields=doc_number`? If you want it handled "automatically" instead of passing in a string you could write an instance for [EncodeQueryParam](https://pursuit.purescript.org/packages/purescript-payload/0.3.1/docs/Payload.Client.QueryParams#t:EncodeQueryParam) for your own type. It would still require passing some query parameter placeholder to the client function, though, and I don't think that part will change.

**Comment by jsparkes** [comment]
Ok, I will continue with the parameterized version workaround.
